### ISSUE TITLE
About the language syntax in featuretools4s file 

### ISSUE THREAD

**Issue by panzhenfu** [pan5431333/featuretools4s#1]
In advance, I'm glad your effort. the grammar syntax in featruetool4s file look like  Scala syntax instead of Python syntax ?  but the  suffix of the file is .py ,is work???

**Comment by pan5431333** [comment]
Hi, I'm not sure I understand your question. But all code in *featuretools4s* is written in Python. There is no Scala code. In Scala you need to start with `val` or `var` to define a new variable and apparently there is no `val` or `var` in file `featuretools4s.py`. Thanks.

**Comment by pan5431333** [comment]
I just realize that you may mean the post-type syntax e.g. `spark: SparkSession`. After Python 3.5 users are able to annotate types for variables so that IDE (e.g. PyCharm) could help to find potential bugs. Please do not hesitate to point out if you have any suggestions towards featuretools4s. Thanks!
